package ru.lavrov.tm.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-03-24T18:25:41.322+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "GeneralCommandsEndpointService",
                  wsdlLocation = "http://localhost:8090/GeneralCommandsEndpoint?wsdl",
                  targetNamespace = "http://endpoint.tm.lavrov.ru/")
public class GeneralCommandsEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.tm.lavrov.ru/", "GeneralCommandsEndpointService");
    public final static QName GeneralCommandsEndpointPort = new QName("http://endpoint.tm.lavrov.ru/", "GeneralCommandsEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/GeneralCommandsEndpoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneralCommandsEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/GeneralCommandsEndpoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneralCommandsEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneralCommandsEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneralCommandsEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GeneralCommandsEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeneralCommandsEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeneralCommandsEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GeneralCommandsEndpoint
     */
    @WebEndpoint(name = "GeneralCommandsEndpointPort")
    public GeneralCommandsEndpoint getGeneralCommandsEndpointPort() {
        return super.getPort(GeneralCommandsEndpointPort, GeneralCommandsEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneralCommandsEndpoint
     */
    @WebEndpoint(name = "GeneralCommandsEndpointPort")
    public GeneralCommandsEndpoint getGeneralCommandsEndpointPort(WebServiceFeature... features) {
        return super.getPort(GeneralCommandsEndpointPort, GeneralCommandsEndpoint.class, features);
    }

}
