package ru.lavrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-03-24T18:25:41.315+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.lavrov.ru/", name = "GeneralCommandsEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneralCommandsEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromJSONByFasterXMLRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromJSONByFasterXMLResponse")
    @RequestWrapper(localName = "dataFromJSONByFasterXML", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromJSONByFasterXML")
    @ResponseWrapper(localName = "dataFromJSONByFasterXMLResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromJSONByFasterXMLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataFromJSONByFasterXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromXMLByJAXBRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromXMLByJAXBResponse")
    @RequestWrapper(localName = "dataFromXMLByJAXB", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromXMLByJAXB")
    @ResponseWrapper(localName = "dataFromXMLByJAXBResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromXMLByJAXBResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataFromXMLByJAXB(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromXMLByFasterXMLRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromXMLByFasterXMLResponse")
    @RequestWrapper(localName = "dataFromXMLByFasterXML", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromXMLByFasterXML")
    @ResponseWrapper(localName = "dataFromXMLByFasterXMLResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromXMLByFasterXMLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataFromXMLByFasterXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/serializeRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/serializeResponse")
    @RequestWrapper(localName = "serialize", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.Serialize")
    @ResponseWrapper(localName = "serializeResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.SerializeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean serialize(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromJSONByJAXBRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataFromJSONByJAXBResponse")
    @RequestWrapper(localName = "dataFromJSONByJAXB", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromJSONByJAXB")
    @ResponseWrapper(localName = "dataFromJSONByJAXBResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataFromJSONByJAXBResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataFromJSONByJAXB(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToJSONByJAXBRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToJSONByJAXBResponse")
    @RequestWrapper(localName = "dataToJSONByJAXB", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToJSONByJAXB")
    @ResponseWrapper(localName = "dataToJSONByJAXBResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToJSONByJAXBResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataToJSONByJAXB(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToJSONByFasterXMLRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToJSONByFasterXMLResponse")
    @RequestWrapper(localName = "dataToJSONByFasterXML", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToJSONByFasterXML")
    @ResponseWrapper(localName = "dataToJSONByFasterXMLResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToJSONByFasterXMLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataToJSONByFasterXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/deserializeRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/deserializeResponse")
    @RequestWrapper(localName = "deserialize", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.Deserialize")
    @ResponseWrapper(localName = "deserializeResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DeserializeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deserialize(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToXMLByFasterXMLRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToXMLByFasterXMLResponse")
    @RequestWrapper(localName = "dataToXMLByFasterXML", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToXMLByFasterXML")
    @ResponseWrapper(localName = "dataToXMLByFasterXMLResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToXMLByFasterXMLResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataToXMLByFasterXML(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToXMLByJAXBRequest", output = "http://endpoint.tm.lavrov.ru/GeneralCommandsEndpoint/dataToXMLByJAXBResponse")
    @RequestWrapper(localName = "dataToXMLByJAXB", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToXMLByJAXB")
    @ResponseWrapper(localName = "dataToXMLByJAXBResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DataToXMLByJAXBResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean dataToXMLByJAXB(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.lavrov.tm.endpoint.Session arg0
    );
}
