package ru.lavrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-04-03T15:05:01.385+03:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.lavrov.ru/", name = "TaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeAllRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeAllResponse")
    @RequestWrapper(localName = "removeAll", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RemoveAll")
    @ResponseWrapper(localName = "removeAllResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RemoveAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeAll(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeTaskByNameRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeTaskByNameResponse")
    @RequestWrapper(localName = "removeTaskByName", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RemoveTaskByName")
    @ResponseWrapper(localName = "removeTaskByNameResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RemoveTaskByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeTaskByName(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksResponse")
    @RequestWrapper(localName = "findAllTasks", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasks")
    @ResponseWrapper(localName = "findAllTasksResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasks(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByStatusRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByStatusResponse")
    @RequestWrapper(localName = "findAllTasksByStatus", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByStatus")
    @ResponseWrapper(localName = "findAllTasksByStatusResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasksByStatus(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByStartDateRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByStartDateResponse")
    @RequestWrapper(localName = "findAllTasksByStartDate", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByStartDate")
    @ResponseWrapper(localName = "findAllTasksByStartDateResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByStartDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasksByStartDate(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/renameTaskRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/renameTaskResponse")
    @RequestWrapper(localName = "renameTask", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RenameTask")
    @ResponseWrapper(localName = "renameTaskResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RenameTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean renameTask(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByNamePartRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByNamePartResponse")
    @RequestWrapper(localName = "findAllTasksByNamePart", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByNamePart")
    @ResponseWrapper(localName = "findAllTasksByNamePartResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByNamePartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasksByNamePart(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByFinishDateRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByFinishDateResponse")
    @RequestWrapper(localName = "findAllTasksByFinishDate", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByFinishDate")
    @ResponseWrapper(localName = "findAllTasksByFinishDateResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByFinishDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasksByFinishDate(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/createByTaskNameRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/createByTaskNameResponse")
    @RequestWrapper(localName = "createByTaskName", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.CreateByTaskName")
    @ResponseWrapper(localName = "createByTaskNameResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.CreateByTaskNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean createByTaskName(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/removeResponse")
    @RequestWrapper(localName = "remove", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RemoveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean remove(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByDescPartRequest", output = "http://endpoint.tm.lavrov.ru/TaskEndpoint/findAllTasksByDescPartResponse")
    @RequestWrapper(localName = "findAllTasksByDescPart", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByDescPart")
    @ResponseWrapper(localName = "findAllTasksByDescPartResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.FindAllTasksByDescPartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.Task> findAllTasksByDescPart(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
