package ru.lavrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-03-18T18:25:11.742+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.lavrov.ru/", name = "TestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TestEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TestEndpoint/calculateRequest", output = "http://endpoint.tm.lavrov.ru/TestEndpoint/calculateResponse")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.CalculateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int calculate(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TestEndpoint/helloRequest", output = "http://endpoint.tm.lavrov.ru/TestEndpoint/helloResponse")
    @RequestWrapper(localName = "hello", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello();

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/TestEndpoint/helloMeRequest", output = "http://endpoint.tm.lavrov.ru/TestEndpoint/helloMeResponse")
    @RequestWrapper(localName = "helloMe", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.HelloMe")
    @ResponseWrapper(localName = "helloMeResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.HelloMeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloMe(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
