package ru.lavrov.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-03-18T18:25:11.995+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.lavrov.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/loginUserRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/loginUserResponse")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.LoginUserResponse")
    public void loginUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/updateLoginRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/updateLoginResponse")
    @RequestWrapper(localName = "updateLogin", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.UpdateLogin")
    @ResponseWrapper(localName = "updateLoginResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.UpdateLoginResponse")
    public void updateLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/updatePasswordRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/updatePasswordResponse")
    @RequestWrapper(localName = "updatePassword", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.UpdatePassword")
    @ResponseWrapper(localName = "updatePasswordResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.UpdatePasswordResponse")
    public void updatePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/logoutUserRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/logoutUserResponse")
    @RequestWrapper(localName = "logoutUser", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.LogoutUser")
    @ResponseWrapper(localName = "logoutUserResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.LogoutUserResponse")
    public void logoutUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/registerUserRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/registerUserResponse")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.RegisterUserResponse")
    public void registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/deleteUserRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/deleteUserResponse")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/helloMeRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/helloMeResponse")
    @RequestWrapper(localName = "helloMe", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.HelloMe")
    @ResponseWrapper(localName = "helloMeResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.HelloMeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloMe(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.lavrov.ru/UserEndpoint/displayUserDataRequest", output = "http://endpoint.tm.lavrov.ru/UserEndpoint/displayUserDataResponse")
    @RequestWrapper(localName = "displayUserData", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DisplayUserData")
    @ResponseWrapper(localName = "displayUserDataResponse", targetNamespace = "http://endpoint.tm.lavrov.ru/", className = "ru.lavrov.tm.endpoint.DisplayUserDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.lavrov.tm.endpoint.ArrayList> displayUserData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
